# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop, develop/** ]
  pull_request:
    branches: [ develop, develop/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout alpha branch
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: init ssh
        env:
          AK: ${{ secrets.IP }}
        run: |
          echo $AK
          echo "=========="
          echo "${{ secrets.SSHKEY }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-keyscan 47.240.51.148 >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.SSHKEY }}"

          # ssh root@${{secrets.SERVER_IP}} "cd /your/workspace/path && sh update.sh "

      # Runs a set of commands using the runners shell
      - name: redeploy alpha server
        run: |
          ssh -p 2223 root@47.240.51.148 "mkdir -p ~/NOWTESTfromEG;"
          echo deployed successfully.
