# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master, master/** ]
  pull_request:
    branches: [ master, master/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout alpha branch
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        with:
          ref: master
      - name: init ssh
        run: |
          echo "${{secrets.YWI_PEM333}}"
          echo "=========="
          echo "${{secrets.SSHKEY}}"
          mkdir -p ~/.ssh
          echo "${{secrets.SSHKEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan 116.63.158.159 >> ~/.ssh/known_hosts

          # ssh root@${{secrets.SERVER_IP}} "cd /your/workspace/path && sh update.sh "

      # Runs a set of commands using the runners shell
      - name: redeploy alpha server
        run: |
          ssh -p 2223 root@116.63.158.159 "mkdir -p ~/NOWTESTfromEG;"
          echo deployed successfully.
